import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import CardCreator from "../../components/CardCreator";
import Header from "../../components/Header";
import Spinner from "../../components/Spinner";
const CreateCard: NextPage = () => {
  const { status, data: sessionData } = useSession();

  status === "unauthenticated" && signIn();
  return (
    <>
      <Head>
        <title>Create Card</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-cyan-600 to-sky-600">
        {status === "unauthenticated" && <Spinner />}
        {status === "authenticated" && <Header sessionDetails={sessionData} />}
        {status === "authenticated" && (
          //
          <div className="flex select-none flex-col">
            <CardCreator userId={sessionData.user?.id} />
          </div>
        )}
      </main>
    </>
  );
};

export default CreateCard;
