/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @typescript-eslint/no-floating-promises */
import { Card } from "@prisma/client";
import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import CardList from "../../components/CardList";
import Header from "../../components/Header";
import Spinner from "../../components/Spinner";
import { api } from "../../utils/api";

const DeleteCard: NextPage = () => {
  const { status, data: sessionData } = useSession();
  status === "unauthenticated" && signIn();

  //Set up useQuery hook
  const { data, refetch } = api.card.get.useQuery(
    { id: sessionData?.user?.id || "" },
    { enabled: false }
  );

  const mutation = api.card.delete.useMutation();

  //Once sessionData is loaded fetch the data from the query
  //And set the array of cards
  useEffect(() => {
    if (sessionData !== null) {
      (async () => {
        await refetch();
      })();
    }
  }, [sessionData]);

  //Method that we pass as prop to container
  //TODO await the mutation ?? -> refetch data, the await isn't working within my trpc?
  const deleteCard = (id: number) => {
    mutation.mutate({
      id: id,
    });
    const timer = setTimeout(() => {
      refetch();
    }, 250);
    return () => clearTimeout(timer);
  };

  return (
    <>
      <Head>
        <title>Delete Card</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center overflow-hidden bg-gradient-to-br from-cyan-600 to-sky-600">
        {status === "unauthenticated" && <Spinner />}
        {status === "authenticated" && <Header sessionDetails={sessionData} />}
        {data !== undefined && data.length !== 0 && (
          <CardList cards={data} deleteMethod={deleteCard} />
        )}
        {data !== undefined && data.length === 0 && (
          <div className="mb-16 flex flex-col">
            <h1 className="text-center text-4xl font-bold text-white md:text-5xl">
              No cards to delete ❌
            </h1>
            <h2 className="text-start text-lg font-thin text-white sm:text-xl md:text-3xl">
              Add some{" "}
              <Link
                href="/card/create"
                className="italic text-blue-300 duration-300 hover:text-blue-100"
              >
                Here
              </Link>
            </h2>
          </div>
        )}
      </main>
    </>
  );
};

export default DeleteCard;
