import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";
import Spinner from "../components/Spinner";

export default function NoRouter() {
  const { status, data: sessionData } = useSession();
  status === "unauthenticated" && signIn();
  return (
    <>
      <Head>
        <title>CardFlip</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-cyan-600 to-sky-600">
        {status === "loading" && <Spinner />}
        {status === "authenticated" && <Header sessionDetails={sessionData} />}
        {status === "authenticated" && (
          <div className="flex select-none flex-col px-4">
            <h1 className="text-5xl font-bold text-white sm:text-6xl md:text-7xl">
              Woopsies ...
            </h1>
            <h2 className="mb-16 text-xl font-thin text-white sm:text-2xl md:text-4xl">
              The page you are looking for does not exist 🤪
            </h2>
          </div>
        )}
      </main>
    </>
  );
}
