/* eslint-disable @typescript-eslint/restrict-template-expressions */
/* eslint-disable @typescript-eslint/no-misused-promises */
/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, useSession } from "next-auth/react";

import Spinner from "../components/Spinner";
import Header from "../components/Header";

const Home: NextPage = () => {
  const { status, data: sessionData } = useSession();
  status === "unauthenticated" && signIn();
  return (
    <>
      <Head>
        <title>CardFlip</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-start bg-gradient-to-br from-cyan-600 to-sky-600 ${
          status === "loading" && "justify-center"
        }`}
      >
        {status === "authenticated" && <Header sessionDetails={sessionData} />}
        {status === "authenticated" && (
          //
          <div className="flex select-none flex-col items-center justify-center py-10">
            <h1 className="text-center text-5xl font-bold tracking-wide text-white">
              Notetaking just got Easier
            </h1>
            <h2 className="pt-1 text-center text-3xl font-thin text-white">
              Take notes, study and keep track of all your info -{" "}
              <Link
                href="/card/create"
                className="italic text-blue-300 duration-300 hover:text-blue-100"
              >
                in one spot
              </Link>
            </h2>
            <hr className="mt-8 w-3/4 opacity-50" />
            <div className="relative flex flex-row justify-center">
              <div className="absolute z-0 mt-8 ml-20 flex h-[27rem] w-[36rem] select-none flex-col overflow-hidden rounded-xl border-2 border-black/25 bg-white opacity-80">
                <input
                  type="text"
                  name="title"
                  disabled
                  className="rounded-t-xl border-b-2 px-4 py-4 outline-none placeholder:italic placeholder:tracking-wider"
                />
                <textarea
                  name="desc"
                  disabled
                  className="h-full resize-none rounded-b-xl px-4 py-4 outline-none placeholder:italic placeholder:tracking-wider"
                />
                <button
                  className="sticky top-full grid items-center rounded-b-lg border-t-2 bg-green-500/75 px-4 py-4 text-white transition-colors"
                  disabled
                >
                  <i className="fa-solid fa-check" />
                </button>
              </div>
              <div className="absolute z-10 mt-12 ml-10 flex h-[27rem] w-[36rem] flex-col overflow-hidden rounded-xl border-2 border-black/25 bg-white opacity-95">
                <input
                  type="text"
                  disabled
                  name="title"
                  className="rounded-t-xl border-b-2 px-4 py-4 outline-none placeholder:italic placeholder:tracking-wider"
                />
                <textarea
                  name="desc"
                  disabled
                  className="h-full resize-none rounded-b-xl px-4 py-4 outline-none placeholder:italic placeholder:tracking-wider"
                />
                <button
                  className="sticky top-full grid items-center rounded-b-lg border-t-2 bg-green-500/75 px-4 py-4 text-white transition-colors"
                  disabled
                >
                  <i className="fa-solid fa-check" />
                </button>
              </div>
              <div className="absolute z-20 mt-16 flex h-[27rem] w-[36rem] flex-col overflow-hidden rounded-xl border-2 border-black/25 bg-white shadow-lg">
                <input
                  type="text"
                  name="title"
                  disabled
                  placeholder="eg. How to make a paper airplane"
                  className="rounded-t-xl border-b-2 px-4 py-4 outline-none placeholder:italic placeholder:tracking-wider"
                />
                <textarea
                  name="desc"
                  disabled
                  placeholder="To make a paper airplane you start by folding in the two top corners until they meet parallel to eachother . . ."
                  className="h-full resize-none rounded-b-xl px-4 py-4 outline-none placeholder:italic placeholder:tracking-wider"
                />
                <button
                  disabled
                  className="sticky top-full grid items-center justify-center rounded-b-lg border-t-2 bg-green-500/75 px-4 py-4 text-white transition-colors"
                >
                  <i className="fa-solid fa-check" />
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Show spinner if content is loading */}
        {status === "loading" && <Spinner />}
      </main>
    </>
  );
};

export default Home;
